name: Continuos Deploy
on: push

jobs:
  continuos-integration:
    runs-on: windows-latest
    strategy:
      matrix:
        mongodb-version: [4.2]
  steps:
    - uses: actions/checkout@v3
    - name: Using Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.6
    - name: run install, build and test
      run: |
        npm run build
        npm run deploy'1